<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HrmBaharu.Application</RootNamespace>
    <AssemblyName>HrmBaharu.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\department.proto" GrpcServices="Client" />
    <Protobuf Include="..\..\cf-grpc-protos\company.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
